name: Event demo 1
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:
  push:
    branches:
      - main
      - "dev-*"
      - "feat/**"
    paths-ignore:
      - ".github/workflows/*"
jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - name: Output event data
        run: echo "{{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install dependencies
        run: npm ci
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "deploying...."
